version: 0.0
OS: linux
files:
  - source: /
  - destination: /var/www/html/deploy
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
